// src/config/gameConfig.js

export const GAME_CONFIG = {
  CANVAS_WIDTH: 400,
  CANVAS_HEIGHT: 600,
  PLAYER_START_X: 200,
  PLAYER_START_Y: 500,
  PLAYER_SIZE: 40,
  PLAYER_SPEED: 5,
  BULLET_SPEED: 5,
  ENEMY_SPEED: 2,
  HOMING_BULLET_SPEED: 3,
  ANGLED_BULLET_SPEED: 6,
  ANGLED_BULLET_ANGLE: 15,
  MAX_HOMING_BULLETS: 3,
  AUTO_SHOOT_INTERVAL: 3000,
  SPAWN_RED_MIN_DELAY: 3000,
  SPAWN_RED_MAX_DELAY: 8000,
  SPAWN_GREEN_INTERVAL: 8000,
  SHOOT_HOMING_INTERVAL: 5000,
  ANGLED_AUTO_SHOOT_INTERVAL: 6000,
};
